
export type Country = {
  name: string;
  dial_code: string;
  code: string;
  flag: string;
  pattern?: RegExp;
};

export const countries: Country[] = [
  { "name": "Afghanistan", "dial_code": "+93", "code": "AF", "flag": "🇦🇫", "pattern": /^\d{9}$/ },
  { "name": "Albania", "dial_code": "+355", "code": "AL", "flag": "🇦🇱", "pattern": /^\d{9}$/ },
  { "name": "Algeria", "dial_code": "+213", "code": "DZ", "flag": "🇩🇿", "pattern": /^\d{9}$/ },
  { "name": "Andorra", "dial_code": "+376", "code": "AD", "flag": "🇦🇩", "pattern": /^\d{6}$/ },
  { "name": "Angola", "dial_code": "+244", "code": "AO", "flag": "🇦🇴", "pattern": /^\d{9}$/ },
  { "name": "Argentina", "dial_code": "+54", "code": "AR", "flag": "🇦🇷", "pattern": /^\d{10}$/ },
  { "name": "Armenia", "dial_code": "+374", "code": "AM", "flag": "🇦🇲", "pattern": /^\d{8}$/ },
  { "name": "Australia", "dial_code": "+61", "code": "AU", "flag": "🇦🇺", "pattern": /^\d{9}$/ },
  { "name": "Austria", "dial_code": "+43", "code": "AT", "flag": "🇦🇹", "pattern": /^\d{10,13}$/ },
  { "name": "Azerbaijan", "dial_code": "+994", "code": "AZ", "flag": "🇦🇿", "pattern": /^\d{9}$/ },
  { "name": "Bahamas", "dial_code": "+1-242", "code": "BS", "flag": "🇧🇸", "pattern": /^\d{10}$/ },
  { "name": "Bahrain", "dial_code": "+973", "code": "BH", "flag": "🇧🇭", "pattern": /^\d{8}$/ },
  { "name": "Bangladesh", "dial_code": "+880", "code": "BD", "flag": "🇧🇩", "pattern": /^\d{10}$/ },
  { "name": "Belarus", "dial_code": "+375", "code": "BY", "flag": "🇧🇾", "pattern": /^\d{9}$/ },
  { "name": "Belgium", "dial_code": "+32", "code": "BE", "flag": "🇧🇪", "pattern": /^\d{9}$/ },
  { "name": "Belize", "dial_code": "+501", "code": "BZ", "flag": "🇧🇿", "pattern": /^\d{7}$/ },
  { "name": "Benin", "dial_code": "+229", "code": "BJ", "flag": "🇧🇯", "pattern": /^\d{8}$/ },
  { "name": "Bhutan", "dial_code": "+975", "code": "BT", "flag": "🇧🇹", "pattern": /^\d{8}$/ },
  { "name": "Bolivia", "dial_code": "+591", "code": "BO", "flag": "🇧🇴", "pattern": /^\d{8}$/ },
  { "name": "Bosnia and Herzegovina", "dial_code": "+387", "code": "BA", "flag": "🇧🇦", "pattern": /^\d{8}$/ },
  { "name": "Botswana", "dial_code": "+267", "code": "BW", "flag": "🇧🇼", "pattern": /^\d{7,8}$/ },
  { "name": "Brazil", "dial_code": "+55", "code": "BR", "flag": "🇧🇷", "pattern": /^\d{10,11}$/ },
  { "name": "Brunei", "dial_code": "+673", "code": "BN", "flag": "🇧🇳", "pattern": /^\d{7}$/ },
  { "name": "Bulgaria", "dial_code": "+359", "code": "BG", "flag": "🇧🇬", "pattern": /^\d{9}$/ },
  { "name": "Burkina Faso", "dial_code": "+226", "code": "BF", "flag": "🇧🇫", "pattern": /^\d{8}$/ },
  { "name": "Cambodia", "dial_code": "+855", "code": "KH", "flag": "🇰🇭", "pattern": /^\d{8,9}$/ },
  { "name": "Cameroon", "dial_code": "+237", "code": "CM", "flag": "🇨🇲", "pattern": /^\d{9}$/ },
  { "name": "Canada", "dial_code": "+1", "code": "CA", "flag": "🇨🇦", "pattern": /^\d{10}$/ },
  { "name": "Central African Republic", "dial_code": "+236", "code": "CF", "flag": "🇨🇫", "pattern": /^\d{8}$/ },
  { "name": "Chad", "dial_code": "+235", "code": "TD", "flag": "🇹🇩", "pattern": /^\d{8}$/ },
  { "name": "Chile", "dial_code": "+56", "code": "CL", "flag": "🇨🇱", "pattern": /^\d{9}$/ },
  { "name": "China", "dial_code": "+86", "code": "CN", "flag": "🇨🇳", "pattern": /^\d{11}$/ },
  { "name": "Colombia", "dial_code": "+57", "code": "CO", "flag": "🇨🇴", "pattern": /^\d{10}$/ },
  { "name": "Congo (Brazzaville)", "dial_code": "+242", "code": "CG", "flag": "🇨🇬", "pattern": /^\d{9}$/ },
  { "name": "Congo (Kinshasa)", "dial_code": "+243", "code": "CD", "flag": "🇨🇩", "pattern": /^\d{9}$/ },
  { "name": "Costa Rica", "dial_code": "+506", "code": "CR", "flag": "🇨🇷", "pattern": /^\d{8}$/ },
  { "name": "Croatia", "dial_code": "+385", "code": "HR", "flag": "🇭🇷", "pattern": /^\d{8,9}$/ },
  { "name": "Cuba", "dial_code": "+53", "code": "CU", "flag": "🇨🇺", "pattern": /^\d{8}$/ },
  { "name": "Cyprus", "dial_code": "+357", "code": "CY", "flag": "🇨🇾", "pattern": /^\d{8}$/ },
  { "name": "Czech Republic", "dial_code": "+420", "code": "CZ", "flag": "🇨🇿", "pattern": /^\d{9}$/ },
  { "name": "Denmark", "dial_code": "+45", "code": "DK", "flag": "🇩🇰", "pattern": /^\d{8}$/ },
  { "name": "Djibouti", "dial_code": "+253", "code": "DJ", "flag": "🇩🇯", "pattern": /^\d{6}$/ },
  { "name": "Dominica", "dial_code": "+1-767", "code": "DM", "flag": "🇩🇲", "pattern": /^\d{7}$/ },
  { "name": "Dominican Republic", "dial_code": "+1-809", "code": "DO", "flag": "🇩🇴", "pattern": /^\d{10}$/ },
  { "name": "Ecuador", "dial_code": "+593", "code": "EC", "flag": "🇪🇨", "pattern": /^\d{9}$/ },
  { "name": "Egypt", "dial_code": "+20", "code": "EG", "flag": "🇪🇬", "pattern": /^\d{10}$/ },
  { "name": "El Salvador", "dial_code": "+503", "code": "SV", "flag": "🇸🇻", "pattern": /^\d{8}$/ },
  { "name": "Estonia", "dial_code": "+372", "code": "EE", "flag": "🇪🇪", "pattern": /^\d{7,8}$/ },
  { "name": "Ethiopia", "dial_code": "+251", "code": "ET", "flag": "🇪🇹", "pattern": /^\d{9}$/ },
  { "name": "Fiji", "dial_code": "+679", "code": "FJ", "flag": "🇫🇯", "pattern": /^\d{7}$/ },
  { "name": "Finland", "dial_code": "+358", "code": "FI", "flag": "🇫🇮", "pattern": /^\d{9,10}$/ },
  { "name": "France", "dial_code": "+33", "code": "FR", "flag": "🇫🇷", "pattern": /^\d{9}$/ },
  { "name": "Gabon", "dial_code": "+241", "code": "GA", "flag": "🇬🇦", "pattern": /^\d{7,8}$/ },
  { "name": "Gambia", "dial_code": "+220", "code": "GM", "flag": "🇬🇲", "pattern": /^\d{7}$/ },
  { "name": "Georgia", "dial_code": "+995", "code": "GE", "flag": "🇬🇪", "pattern": /^\d{9}$/ },
  { "name": "Germany", "dial_code": "+49", "code": "DE", "flag": "🇩🇪", "pattern": /^\d{10,11}$/ },
  { "name": "Ghana", "dial_code": "+233", "code": "GH", "flag": "🇬🇭", "pattern": /^\d{9}$/ },
  { "name": "Greece", "dial_code": "+30", "code": "GR", "flag": "🇬🇷", "pattern": /^\d{10}$/ },
  { "name": "Guatemala", "dial_code": "+502", "code": "GT", "flag": "🇬🇹", "pattern": /^\d{8}$/ },
  { "name": "Guinea", "dial_code": "+224", "code": "GN", "flag": "🇬🇳", "pattern": /^\d{9}$/ },
  { "name": "Guyana", "dial_code": "+592", "code": "GY", "flag": "🇬🇾", "pattern": /^\d{7}$/ },
  { "name": "Haiti", "dial_code": "+509", "code": "HT", "flag": "🇭🇹", "pattern": /^\d{8}$/ },
  { "name": "Honduras", "dial_code": "+504", "code": "HN", "flag": "🇭🇳", "pattern": /^\d{8}$/ },
  { "name": "Hong Kong", "dial_code": "+852", "code": "HK", "flag": "🇭🇰", "pattern": /^\d{8}$/ },
  { "name": "Hungary", "dial_code": "+36", "code": "HU", "flag": "🇭🇺", "pattern": /^\d{9}$/ },
  { "name": "Iceland", "dial_code": "+354", "code": "IS", "flag": "🇮🇸", "pattern": /^\d{7}$/ },
  { "name": "India", "dial_code": "+91", "code": "IN", "flag": "🇮🇳", "pattern": /^\d{10}$/ },
  { "name": "Indonesia", "dial_code": "+62", "code": "ID", "flag": "🇮🇩", "pattern": /^\d{9,12}$/ },
  { "name": "Iran", "dial_code": "+98", "code": "IR", "flag": "🇮🇷", "pattern": /^\d{10}$/ },
  { "name": "Iraq", "dial_code": "+964", "code": "IQ", "flag": "🇮🇶", "pattern": /^\d{10}$/ },
  { "name": "Ireland", "dial_code": "+353", "code": "IE", "flag": "🇮🇪", "pattern": /^\d{9}$/ },
  { "name": "Israel", "dial_code": "+972", "code": "IL", "flag": "🇮🇱", "pattern": /^\d{9}$/ },
  { "name": "Italy", "dial_code": "+39", "code": "IT", "flag": "🇮🇹", "pattern": /^\d{10}$/ },
  { "name": "Jamaica", "dial_code": "+1-876", "code": "JM", "flag": "🇯🇲", "pattern": /^\d{7}$/ },
  { "name": "Japan", "dial_code": "+81", "code": "JP", "flag": "🇯🇵", "pattern": /^\d{10}$/ },
  { "name": "Jordan", "dial_code": "+962", "code": "JO", "flag": "🇯🇴", "pattern": /^\d{9}$/ },
  { "name": "Kazakhstan", "dial_code": "+7", "code": "KZ", "flag": "🇰🇿", "pattern": /^\d{10}$/ },
  { "name": "Kenya", "dial_code": "+254", "code": "KE", "flag": "🇰🇪", "pattern": /^\d{9}$/ },
  { "name": "Kuwait", "dial_code": "+965", "code": "KW", "flag": "🇰🇼", "pattern": /^\d{8}$/ },
  { "name": "Kyrgyzstan", "dial_code": "+996", "code": "KG", "flag": "🇰🇬", "pattern": /^\d{9}$/ },
  { "name": "Laos", "dial_code": "+856", "code": "LA", "flag": "🇱🇦", "pattern": /^\d{10}$/ },
  { "name": "Latvia", "dial_code": "+371", "code": "LV", "flag": "🇱🇻", "pattern": /^\d{8}$/ },
  { "name": "Lebanon", "dial_code": "+961", "code": "LB", "flag": "🇱🇧", "pattern": /^\d{7,8}$/ },
  { "name": "Liberia", "dial_code": "+231", "code": "LR", "flag": "🇱🇷", "pattern": /^\d{7,9}$/ },
  { "name": "Libya", "dial_code": "+218", "code": "LY", "flag": "🇱🇾", "pattern": /^\d{9}$/ },
  { "name": "Liechtenstein", "dial_code": "+423", "code": "LI", "flag": "🇱🇮", "pattern": /^\d{7}$/ },
  { "name": "Lithuania", "dial_code": "+370", "code": "LT", "flag": "🇱🇹", "pattern": /^\d{8}$/ },
  { "name": "Luxembourg", "dial_code": "+352", "code": "LU", "flag": "🇱🇺", "pattern": /^\d{9}$/ },
  { "name": "Macedonia", "dial_code": "+389", "code": "MK", "flag": "🇲🇰", "pattern": /^\d{8}$/ },
  { "name": "Madagascar", "dial_code": "+261", "code": "MG", "flag": "🇲🇬", "pattern": /^\d{9}$/ },
  { "name": "Malaysia", "dial_code": "+60", "code": "MY", "flag": "🇲🇾", "pattern": /^\d{9,10}$/ },
  { "name": "Maldives", "dial_code": "+960", "code": "MV", "flag": "🇲🇻", "pattern": /^\d{7}$/ },
  { "name": "Mali", "dial_code": "+223", "code": "ML", "flag": "🇲🇱", "pattern": /^\d{8}$/ },
  { "name": "Malta", "dial_code": "+356", "code": "MT", "flag": "🇲🇹", "pattern": /^\d{8}$/ },
  { "name": "Mauritania", "dial_code": "+222", "code": "MR", "flag": "🇲🇷", "pattern": /^\d{8}$/ },
  { "name": "Mexico", "dial_code": "+52", "code": "MX", "flag": "🇲🇽", "pattern": /^\d{10}$/ },
  { "name": "Moldova", "dial_code": "+373", "code": "MD", "flag": "🇲🇩", "pattern": /^\d{8}$/ },
  { "name": "Monaco", "dial_code": "+377", "code": "MC", "flag": "🇲🇨", "pattern": /^\d{8,9}$/ },
  { "name": "Mongolia", "dial_code": "+976", "code": "MN", "flag": "🇲🇳", "pattern": /^\d{8}$/ },
  { "name": "Montenegro", "dial_code": "+382", "code": "ME", "flag": "🇲🇪", "pattern": /^\d{8}$/ },
  { "name": "Morocco", "dial_code": "+212", "code": "MA", "flag": "🇲🇦", "pattern": /^\d{9}$/ },
  { "name": "Myanmar", "dial_code": "+95", "code": "MM", "flag": "🇲🇲", "pattern": /^\d{8,10}$/ },
  { "name": "Namibia", "dial_code": "+264", "code": "NA", "flag": "🇳🇦", "pattern": /^\d{9}$/ },
  { "name": "Nepal", "dial_code": "+977", "code": "NP", "flag": "🇳🇵", "pattern": /^\d{10}$/ },
  { "name": "Netherlands", "dial_code": "+31", "code": "NL", "flag": "🇳🇱", "pattern": /^\d{9}$/ },
  { "name": "New Zealand", "dial_code": "+64", "code": "NZ", "flag": "🇳🇿", "pattern": /^\d{8,10}$/ },
  { "name": "Nicaragua", "dial_code": "+505", "code": "NI", "flag": "🇳🇮", "pattern": /^\d{8}$/ },
  { "name": "Niger", "dial_code": "+227", "code": "NE", "flag": "🇳🇪", "pattern": /^\d{8}$/ },
  { "name": "Nigeria", "dial_code": "+234", "code": "NG", "flag": "🇳🇬", "pattern": /^\d{10}$/ },
  { "name": "North Korea", "dial_code": "+850", "code": "KP", "flag": "🇰🇵", "pattern": /^\d{4,10}$/ },
  { "name": "Norway", "dial_code": "+47", "code": "NO", "flag": "🇳🇴", "pattern": /^\d{8}$/ },
  { "name": "Oman", "dial_code": "+968", "code": "OM", "flag": "🇴🇲", "pattern": /^\d{8}$/ },
  { "name": "Pakistan", "dial_code": "+92", "code": "PK", "flag": "🇵🇰", "pattern": /^\d{10}$/ },
  { "name": "Palestine", "dial_code": "+970", "code": "PS", "flag": "🇵🇸", "pattern": /^\d{9}$/ },
  { "name": "Panama", "dial_code": "+507", "code": "PA", "flag": "🇵🇦", "pattern": /^\d{7,8}$/ },
  { "name": "Paraguay", "dial_code": "+595", "code": "PY", "flag": "🇵🇾", "pattern": /^\d{9}$/ },
  { "name": "Peru", "dial_code": "+51", "code": "PE", "flag": "🇵🇪", "pattern": /^\d{9}$/ },
  { "name": "Philippines", "dial_code": "+63", "code": "PH", "flag": "🇵🇭", "pattern": /^\d{10}$/ },
  { "name": "Poland", "dial_code": "+48", "code": "PL", "flag": "🇵🇱", "pattern": /^\d{9}$/ },
  { "name": "Portugal", "dial_code": "+351", "code": "PT", "flag": "🇵🇹", "pattern": /^\d{9}$/ },
  { "name": "Qatar", "dial_code": "+974", "code": "QA", "flag": "🇶🇦", "pattern": /^\d{8}$/ },
  { "name": "Romania", "dial_code": "+40", "code": "RO", "flag": "🇷🇴", "pattern": /^\d{9}$/ },
  { "name": "Russia", "dial_code": "+7", "code": "RU", "flag": "🇷🇺", "pattern": /^\d{10}$/ },
  { "name": "Rwanda", "dial_code": "+250", "code": "RW", "flag": "🇷🇼", "pattern": /^\d{9}$/ },
  { "name": "Saudi Arabia", "dial_code": "+966", "code": "SA", "flag": "🇸🇦", "pattern": /^\d{9}$/ },
  { "name": "Senegal", "dial_code": "+221", "code": "SN", "flag": "🇸🇳", "pattern": /^\d{9}$/ },
  { "name": "Serbia", "dial_code": "+381", "code": "RS", "flag": "🇷🇸", "pattern": /^\d{8,9}$/ },
  { "name": "Singapore", "dial_code": "+65", "code": "SG", "flag": "🇸🇬", "pattern": /^\d{8}$/ },
  { "name": "Slovakia", "dial_code": "+421", "code": "SK", "flag": "🇸🇰", "pattern": /^\d{9}$/ },
  { "name": "Slovenia", "dial_code": "+386", "code": "SI", "flag": "🇸🇮", "pattern": /^\d{8}$/ },
  { "name": "Somalia", "dial_code": "+252", "code": "SO", "flag": "🇸🇴", "pattern": /^\d{7,8}$/ },
  { "name": "South Africa", "dial_code": "+27", "code": "ZA", "flag": "🇿🇦", "pattern": /^\d{9}$/ },
  { "name": "South Korea", "dial_code": "+82", "code": "KR", "flag": "🇰🇷", "pattern": /^\d{9,11}$/ },
  { "name": "Spain", "dial_code": "+34", "code": "ES", "flag": "🇪🇸", "pattern": /^\d{9}$/ },
  { "name": "Sri Lanka", "dial_code": "+94", "code": "LK", "flag": "🇱🇰", "pattern": /^\d{9}$/ },
  { "name": "Sudan", "dial_code": "+249", "code": "SD", "flag": "🇸🇩", "pattern": /^\d{9}$/ },
  { "name": "Sweden", "dial_code": "+46", "code": "SE", "flag": "🇸🇪", "pattern": /^\d{9,10}$/ },
  { "name": "Switzerland", "dial_code": "+41", "code": "CH", "flag": "🇨🇭", "pattern": /^\d{9}$/ },
  { "name": "Syria", "dial_code": "+963", "code": "SY", "flag": "🇸🇾", "pattern": /^\d{9}$/ },
  { "name": "Taiwan", "dial_code": "+886", "code": "TW", "flag": "🇹🇼", "pattern": /^\d{9}$/ },
  { "name": "Tanzania", "dial_code": "+255", "code": "TZ", "flag": "🇹🇿", "pattern": /^\d{9}$/ },
  { "name": "Thailand", "dial_code": "+66", "code": "TH", "flag": "🇹🇭", "pattern": /^\d{9}$/ },
  { "name": "Togo", "dial_code": "+228", "code": "TG", "flag": "🇹🇬", "pattern": /^\d{8}$/ },
  { "name": "Tunisia", "dial_code": "+216", "code": "TN", "flag": "🇹🇳", "pattern": /^\d{8}$/ },
  { "name": "Turkey", "dial_code": "+90", "code": "TR", "flag": "🇹🇷", "pattern": /^\d{10}$/ },
  { "name": "Uganda", "dial_code": "+256", "code": "UG", "flag": "🇺🇬", "pattern": /^\d{9}$/ },
  { "name": "Ukraine", "dial_code": "+380", "code": "UA", "flag": "🇺🇦", "pattern": /^\d{9}$/ },
  { "name": "United Arab Emirates", "dial_code": "+971", "code": "AE", "flag": "🇦🇪", "pattern": /^\d{9}$/ },
  { "name": "United Kingdom", "dial_code": "+44", "code": "GB", "flag": "🇬🇧", "pattern": /^\d{10}$/ },
  { "name": "United States", "dial_code": "+1", "code": "US", "flag": "🇺🇸", "pattern": /^\d{10}$/ },
  { "name": "Uruguay", "dial_code": "+598", "code": "UY", "flag": "🇺🇾", "pattern": /^\d{8}$/ },
  { "name": "Uzbekistan", "dial_code": "+998", "code": "UZ", "flag": "🇺🇿", "pattern": /^\d{9}$/ },
  { "name": "Venezuela", "dial_code": "+58", "code": "VE", "flag": "🇻🇪", "pattern": /^\d{10}$/ },
  { "name": "Vietnam", "dial_code": "+84", "code": "VN", "flag": "🇻🇳", "pattern": /^\d{9,10}$/ },
  { "name": "Yemen", "dial_code": "+967", "code": "YE", "flag": "🇾🇪", "pattern": /^\d{9}$/ },
  { "name": "Zambia", "dial_code": "+260", "code": "ZM", "flag": "🇿🇲", "pattern": /^\d{9}$/ },
  { "name": "Zimbabwe", "dial_code": "+263", "code": "ZW", "flag": "🇿🇼", "pattern": /^\d{9}$/ },
];
