
// This script is intended to be used by a Flutter application's build process.
// It fetches the Firebase configuration from the environment and makes it
// available for the Flutter app's initialization.

const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

// This is a placeholder for the Flutter app's lib directory.
// In a real CI/CD pipeline, this path would point to the actual Flutter project.
const flutterLibPath = path.resolve(__dirname, '../src/lib/flutter_generated'); 
const outputFilePath = path.resolve(flutterLibPath, 'firebase_options.dart');

// Ensure the directory exists
if (!fs.existsSync(flutterLibPath)) {
  fs.mkdirSync(flutterLibPath, { recursive: true });
}

// These values are read from the .env file at the root of the Next.js project.
const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
};

// Check if all required environment variables are present
const missingKeys = Object.entries(firebaseConfig).filter(([, value]) => !value);

if (missingKeys.length > 0) {
    console.error('Error: Missing Firebase configuration in .env file.');
    missingKeys.forEach(([key]) => console.error(` - ${key.replace('NEXT_PUBLIC_', 'NEXT_PUBLIC_')}`));
    process.exit(1);
}

const dartFileContent = `
// File generated by firebase-config.js. Do not edit.
// This file is used by the Flutter app to connect to the same Firebase backend as the web app.

import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // In a real-world scenario, you would have different options for
    // iOS and Android, but for this integration, we'll use the same
    // web-based config as a starting point.
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '${firebaseConfig.apiKey}',
    appId: '${firebaseConfig.appId}',
    messagingSenderId: '${firebaseConfig.messagingSenderId}',
    projectId: '${firebaseConfig.projectId}',
    authDomain: '${firebaseConfig.authDomain}',
    databaseURL: '${firebaseConfig.databaseURL}',
    storageBucket: '${firebaseConfig.storageBucket}',
    measurementId: '${firebaseConfig.measurementId}',
  );

  // You would add Android and iOS specific options here.
  // static const FirebaseOptions android = FirebaseOptions(...);
  // static const FirebaseOptions ios = FirebaseOptions(...);
}
`;

fs.writeFileSync(outputFilePath, dartFileContent.trim());

console.log(`Successfully generated Flutter Firebase options at: ${outputFilePath}`);

